server.port=${PORT:8084}
# =========================
# RabbitMQ Configuration
# =========================
spring.rabbitmq.addresses=${CLOUDAMQP_URL:amqps://tvedsvug:k-0mPQ84l94C_Sg3I95qONez0pQXoMAM@cow.rmq2.cloudamqp.com/tvedsvug}

logging.level.com.last.call.schedulerservice= INFO
logging.level.org.springframework.kafka= INFO
logging.level.org.quartz= INFO