FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /build

COPY pom.xml ./pom.xml
COPY shared-dtos ./shared-dtos
COPY room-service ./room-service

RUN mvn install:install-file -Dfile=pom.xml -DgroupId=com.last.call -DartifactId=backend -Dversion=0.0.1-SNAPSHOT -Dpackaging=pom && \
    mvn clean install -DskipTests -f shared-dtos/pom.xml && \
    mvn clean package -DskipTests -f room-service/pom.xml

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY --from=build /build/room-service/target/room-service-*.jar app.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "app.jar"]
