FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /build

COPY pom.xml ./pom.xml
COPY shared-dtos ./shared-dtos
COPY scheduler-service ./scheduler-service

RUN mvn clean install -DskipTests -f shared-dtos/pom.xml && \
    mvn clean package -DskipTests -f scheduler-service/pom.xml

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY --from=build /build/scheduler-service/target/scheduler-service-*.jar app.jar

EXPOSE 8084

ENTRYPOINT ["java", "-jar", "app.jar"]
