# =========================
# Server Configuration
# =========================
spring.application.name=room-service
server.port=${PORT:8083}

# =========================
# Spring Datasource (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:last_call_room_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Logging
# =========================
logging.level.org.springframework=INFO
logging.level.com.bidding.user=DEBUG

# =========================
# RabbitMQ Configuration
# =========================
spring.rabbitmq.addresses=${CLOUDAMQP_URL:amqps://tvedsvug:k-0mPQ84l94C_Sg3I95qONez0pQXoMAM@cow.rmq2.cloudamqp.com/tvedsvug}