FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /build
RUN echo pwd
RUN echo ls -la

COPY shared-dtos ./shared-dtos
COPY gateway-service ./gateway-service

RUN mvn clean package -DskipTests -pl gateway-service -am

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY --from=build /build/gateway-service/target/gateway-service-*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]